"""-m

Revision ID: 2142d4875055
Revises: 7b42025f1402
Create Date: 2022-11-09 15:26:39.169292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2142d4875055'
down_revision = '7b42025f1402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'account_number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=19),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'account_number',
               existing_type=sa.String(length=19),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
