"""-m

Revision ID: 7b42025f1402
Revises: 66b7ac48fc87
Create Date: 2022-11-09 15:14:17.991548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b42025f1402'
down_revision = '66b7ac48fc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('expire_date', sa.Date(), nullable=True))
    op.drop_column('accounts', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'expire_date')
    # ### end Alembic commands ###
