"""-m

Revision ID: c6e67fa6ddaf
Revises: 0c2730b04dea
Create Date: 2022-11-13 12:34:32.649695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e67fa6ddaf'
down_revision = '0c2730b04dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listitems', sa.Column('prefix', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listitems', 'prefix')
    # ### end Alembic commands ###
